const express = require('express');
const PDFDocument = require('pdfkit');
const pool = require("../../db"); 

const authenticateJWT = require('../../middleware/auth');

const router = express.Router();

let invoiceCounter = 1;

// Function to generate invoice number
function generateInvoiceNo() {
  const today = new Date();
  const yyyy = today.getFullYear();
  const mm = String(today.getMonth() + 1).padStart(2, '0');
  const dd = String(today.getDate()).padStart(2, '0');
  const datePart = `${yyyy}${mm}${dd}`;
  const counterPart = String(invoiceCounter).padStart(3, '0'); // e.g., 001, 002
  invoiceCounter++;
  return `INV${datePart}-${counterPart}`;
}

// POST: Generate Invoice (direct PDF response)
router.post('/generate', authenticateJWT, async (req, res) => {
  try {
    const invoiceData = req.body;

    // Get employee info from JWT
    const employeeId = req.user.id;

    // Fetch full employee name from DB
    const employeeResult = await pool.query(
      "SELECT full_name FROM employees WHERE id = $1",
      [employeeId]
    );
    const employeeName = employeeResult.rows[0]?.full_name || 'Unknown';

    // Auto-generate invoice number
    const invoiceNo = generateInvoiceNo();
    invoiceData.invoiceNo = invoiceNo;

    // Set response headers so browser/Postman knows it's a PDF
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename=Invoice-${invoiceNo}.pdf`
    );

    // Create PDF document
    const doc = new PDFDocument({ margin: 30 });
    doc.pipe(res); // Pipe directly to response

    // Title
    doc.fontSize(20).text('Medicine Store Invoice', { align: 'center' });
    doc.moveDown();

    // Invoice & patient info
    doc.fontSize(12).text(`Invoice No: ${invoiceData.invoiceNo}`);
    doc.text(`Date: ${invoiceData.date || new Date().toLocaleDateString()}`);
    doc.text(`Patient Name: ${invoiceData.patientName}`);
    doc.text(`Patient Age: ${invoiceData.patientAge || 'N/A'}`);
    doc.text(`Patient Phone: ${invoiceData.patientPhone || 'N/A'}`);
    doc.text(`Generated By: ${employeeName}`); // ✅ Added employee name
    doc.moveDown();

    // Table headers
    const tableTop = 180;
    const itemX = 50;
    const qtyX = 250;
    const priceX = 300;
    const totalX = 400;

    doc.font('Helvetica-Bold');
    doc.text('Medicine', itemX, tableTop);
    doc.text('Qty', qtyX, tableTop);
    doc.text('Unit Price', priceX, tableTop);
    doc.text('Total', totalX, tableTop);
    doc.moveTo(itemX, tableTop + 15).lineTo(500, tableTop + 15).stroke();

    // Table rows
    doc.font('Helvetica');
    let rowY = tableTop + 25;
    invoiceData.medicines.forEach((med) => {
      doc.text(med.name, itemX, rowY);
      doc.text(med.qty, qtyX, rowY);
      doc.text(med.unitPrice, priceX, rowY);
      doc.text(med.total, totalX, rowY);
      rowY += 20;
    });

    // Totals
    doc.moveDown(2);
    doc.text(`Subtotal: ${invoiceData.subtotal}`, { align: 'right' });
    doc.text(`Discount: ${invoiceData.discount}`, { align: 'right' });
    doc.text(`Tax: ${invoiceData.tax}`, { align: 'right' });
    doc.text(`Grand Total: ${invoiceData.grandTotal}`, { align: 'right' });
    doc.text(`Payment Mode: ${invoiceData.paymentMode}`, { align: 'right' });

    // End and send PDF
    doc.end();

  } catch (error) {
    console.error("Invoice generation error:", error.message);
    res.status(500).json({ error: "Server error" });
  }
});

module.exports = router;
