const express = require('express');
const PDFDocument = require('pdfkit');
const pool = require("../../db"); 

const router = express.Router();

let invoiceCounter = 1;

// Function to generate invoice number
function generateInvoiceNo() {
  const today = new Date();
  const yyyy = today.getFullYear();
  const mm = String(today.getMonth() + 1).padStart(2, '0');
  const dd = String(today.getDate()).padStart(2, '0');
  const datePart = `${yyyy}${mm}${dd}`;
  const counterPart = String(invoiceCounter).padStart(3, '0');
  invoiceCounter++;
  return `INV${datePart}-${counterPart}`;
}

// POST: Generate Invoice (direct PDF response)
router.post('/generate', async (req, res) => {
  try {
    const { employeeId, patientName, patientAge, patientPhone, paymentMode } = req.body;

    if (!employeeId) {
      return res.status(400).json({ error: "Employee ID is required" });
    }

    // Fetch full employee name
    const employeeResult = await pool.query(
      "SELECT full_name FROM employees WHERE id = $1",
      [employeeId]
    );
    const employeeName = employeeResult.rows[0]?.full_name || 'Unknown';

    // Fetch cart items for the employee
    const cartResult = await pool.query(
      `SELECT id, name, quantity, price
       FROM cart
       WHERE employeeid = $1`,
      [employeeId]
    );

    // Map cart items to medicines for PDF
    const medicines = cartResult.rows.map(item => ({
      name: item.name,
      qty: item.quantity,
      unitPrice: parseFloat(item.price),
      total: parseFloat(item.price) * item.quantity
    }));

    // Calculate total
    const total = medicines.reduce((sum, med) => sum + med.total, 0);

    // Generate invoice number
    const invoiceNo = generateInvoiceNo();

    // Set response headers for PDF
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Invoice-${invoiceNo}.pdf`);

    // Create PDF
    const doc = new PDFDocument({ margin: 30 });
    doc.pipe(res);

    // Invoice header
    doc.fontSize(20).text('Medicine Store Invoice', { align: 'center' });
    doc.moveDown();

    doc.fontSize(12).text(`Invoice No: ${invoiceNo}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.text(`Patient Name: ${patientName}`);
    doc.text(`Patient Age: ${patientAge || 'N/A'}`);
    doc.text(`Patient Phone: ${patientPhone || 'N/A'}`);
    doc.text(`Generated By: ${employeeName}`);
    doc.moveDown();

    // Table headers
    const tableTop = 180;
    const itemX = 50;
    const qtyX = 250;
    const priceX = 300;
    const totalX = 400;

    doc.font('Helvetica-Bold');
    doc.text('Medicine', itemX, tableTop);
    doc.text('Qty', qtyX, tableTop);
    doc.text('Unit Price', priceX, tableTop);
    doc.text('Total', totalX, tableTop);
    doc.moveTo(itemX, tableTop + 15).lineTo(500, tableTop + 15).stroke();

    // Table rows
    doc.font('Helvetica');
    let rowY = tableTop + 25;
    medicines.forEach(med => {
      doc.text(med.name, itemX, rowY);
      doc.text(med.qty, qtyX, rowY);
      doc.text(med.unitPrice.toFixed(2), priceX, rowY);
      doc.text(med.total.toFixed(2), totalX, rowY);
      rowY += 20;
    });

    // Totals
    doc.moveDown(2);
    doc.text(`Total: ${total.toFixed(2)}`, { align: 'right' });
    doc.text(`Payment Mode: ${paymentMode}`, { align: 'right' });

    doc.end();

  } catch (error) {
    console.error("Invoice generation error:", error.message);
    res.status(500).json({ error: "Server error" });
  }
});

module.exports = router;
